backend:
  name: github
  repo: wolfrobert35/netlifycms

media_folder: static/assets

collections:
  - name: "mirror"
    label: "Zrcadlo"
    folder: "src/pages/mirror"
    create: true
    extension: json
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "mirror"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cena v CZK", name: "cena", widget: "number"}
      - {label: "Price in EUR", name: "price", widget: "number"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "photography"
    label: "Fotka"
    folder: "src/pages/photography"
    create: true
    extension: json
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "photography"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cena v CZK", name: "cena", widget: "number"}
      - {label: "Price in EUR", name: "price", widget: "number"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "jewellery"
    label: "Šprek"
    folder: "src/pages/jewellery"
    create: true
    extension: json
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "jewellery"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cena v CZK", name: "cena", widget: "number"}
      - {label: "Price in EUR", name: "price", widget: "number"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "glass"
    label: "Sklo"
    folder: "src/pages/glass"
    create: true
    extension: json
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "glass"}
      - {label: "Název", name: "nazev", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Cena v CZK", name: "cena", widget: "number"}
      - {label: "Price in EUR", name: "price", widget: "number"}
      - {label: "Obrázek", name: "thumbnail", widget: "image"}

  - name: "general"
    label: "Obecně"
    files:
      - file: "src/pages/index.md"
        label: "Hlavní stránka"
        name: "frontpage"
        extension: json
        fields:
          - label: "O nás"
            name: "about"
            widget: "object"
            fields:
              - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
              - {label: "Popis", name: "popis", widget: "text"}
              - {label: "Description", name: "description", widget: "text"}
          - label: "Kontakt"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact"}
              - {label: "Kontaktní email", name: "mail", widget: "string"}
              - {label: "Telefoní číslo", name: "phone", widget: "string"}
              - {label: "Facebook", name: "facebook", widget: "string"}
              - {label: "Instagram", name: "instagram", widget: "string"}
          - label: "Objednávka"
            name: "order"
            widget: "object"
            fields:
              - {label: "Template Key", name: "templateKey", widget: "hidden", default: "order"}
              - {label: "Informace česky", name: "mail", widget: "text"}
              - {label: "English instrucitons", name: "facebook", widget: "text"}
